#!/bin/bash

HERE="$(dirname "$(readlink -f "${0}")")"

# C locale is used to avoid errors parsing floating point numbers
# in locales that use decimal comma
LC_NUMERIC=C \
LD_LIBRARY_PATH=${HERE}/usr/lib:${HERE}:$LD_LIBRARY_PATH \
${HERE}/usr/bin/emsim $*

